backend: 
  name: github
  repo: Anadea/anadea_jobs
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: "jobs"
    label: "jobs"
    folder: "src/markdown-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
      - label: "Location"
        name: "location"
      - label: "IsActive"
        name: "isActive"
      - label: "Intro"
        name: "intro"
        required: false
      - label: "LinkedIn"
        name: "linkedIn"
        required: false
      - label: "Details"
        name: "detail"
        widget: "markdown"

